spring:
  application:
    name: online-store-orders
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/your_database}
    username: ${DB_USERNAME:your_username}
    password: ${DB_PASSWORD:your_password}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8083
